'use strict';

const fs   = require('fs');
const path = require('path');

/**
 * EarthquakeDataManager
 *
 * Loads an earthquake snapshot (generated by import-earthquakes.js) and
 * provides search/filter/lookup methods.
 *
 * Snapshot shape:
 *   { fetchedUtc, feed, earthquakes[], totalCount, nearVolcanoCount }
 *
 * Each earthquake:
 *   id, magnitude, magnitudeType, place, time, updated, url,
 *   latitude, longitude, depth, felt, cdi, mmi, alert, tsunami,
 *   significance, status, type, title, nearestVolcano?
 */
class EarthquakeDataManager {
  /** @param {string} dataPath  Directory containing earthquakes.json */
  constructor(dataPath) {
    this.dataPath = dataPath;
    /** @type {object[]} */
    this.earthquakes = [];
    this.fetchedUtc  = null;
    this.feed        = null;
  }

  async load() {
    const file = path.join(this.dataPath, 'earthquakes.json');
    if (!fs.existsSync(file)) return;

    const snapshot = JSON.parse(fs.readFileSync(file, 'utf8'));
    this.earthquakes = snapshot.earthquakes || [];
    this.fetchedUtc  = snapshot.fetchedUtc  || null;
    this.feed        = snapshot.feed        || null;
  }

  /** @returns {number} */
  count() { return this.earthquakes.length; }

  /** @returns {number} */
  nearVolcanoCount() {
    return this.earthquakes.filter(e => e.nearestVolcano).length;
  }

  /**
   * Search and filter earthquakes.
   *
   * @param {object} filters
   * @param {number}  [filters.minMagnitude]
   * @param {number}  [filters.maxMagnitude]
   * @param {number}  [filters.minDepth]
   * @param {number}  [filters.maxDepth]
   * @param {boolean} [filters.nearVolcano]   Only earthquakes with nearestVolcano set
   * @param {boolean} [filters.tsunamiOnly]
   * @param {string}  [filters.alert]         PAGER alert level: green|yellow|orange|red
   * @param {number}  [filters.volcanoNumber] Only near a specific volcano
   * @param {number}  [filters.limit]         Default 100
   * @param {number}  [filters.offset]        Default 0
   * @returns {{ earthquakes: object[], total: number, filters: object }}
   */
  search(filters = {}) {
    const matched = this.earthquakes.filter(e => {
      if (filters.minMagnitude != null && e.magnitude < filters.minMagnitude) return false;
      if (filters.maxMagnitude != null && e.magnitude > filters.maxMagnitude) return false;
      if (filters.minDepth     != null && e.depth     < filters.minDepth)     return false;
      if (filters.maxDepth     != null && e.depth     > filters.maxDepth)     return false;
      if (filters.tsunamiOnly  && !e.tsunami)                                  return false;
      if (filters.nearVolcano  && !e.nearestVolcano)                           return false;
      if (filters.alert        && e.alert !== filters.alert)                   return false;
      if (filters.volcanoNumber != null &&
          e.nearestVolcano?.volcanoNumber !== Number(filters.volcanoNumber))    return false;
      return true;
    });

    const offset = Number(filters.offset) || 0;
    const limit  = Number(filters.limit)  || 100;

    return { earthquakes: matched.slice(offset, offset + limit), total: matched.length, filters };
  }

  /**
   * Get all earthquakes near a specific volcano.
   * @param {number} volcanoNumber
   * @returns {object[]}
   */
  nearVolcano(volcanoNumber) {
    const n = Number(volcanoNumber);
    return this.earthquakes.filter(e => e.nearestVolcano?.volcanoNumber === n);
  }
}

module.exports = EarthquakeDataManager;
