'use strict';

const fs = require('fs');
const path = require('path');

/**
 * VolcanoDataManager
 *
 * Loads volcano and eruption data from JSON files (generated by the import
 * scripts) and provides search/filter/lookup methods.
 *
 * Data shape mirrors the GVP (Global Volcanism Program) source:
 *   volcanoNumber, volcanoName, country, volcanicRegionGroup, volcanicRegion,
 *   volcanoLandform, primaryVolcanoType, activityEvidence, lastKnownEruption,
 *   latitude, longitude, elevation, dominantRockType, tectonicSetting,
 *   epoch ("Holocene"|"Pleistocene"), geologicalSummary?, primaryPhotoLink?
 */
class VolcanoDataManager {
  /** @param {string} dataPath  Directory containing volcanoes.json, eruptions.json */
  constructor(dataPath) {
    this.dataPath = dataPath;
    /** @type {Map<number, object>} keyed by volcanoNumber */
    this.volcanoes = new Map();
    /** @type {object[]} */
    this.eruptions = [];
  }

  /**
   * Load data files from disk. Called once during register().
   */
  async load() {
    const volcanoesFile = path.join(this.dataPath, 'volcanoes.json');
    const eruptionsFile = path.join(this.dataPath, 'eruptions.json');

    if (fs.existsSync(volcanoesFile)) {
      const raw = fs.readFileSync(volcanoesFile, 'utf8');
      const arr = JSON.parse(raw);
      this.volcanoes.clear();
      for (const v of arr) {
        this.volcanoes.set(v.volcanoNumber, v);
      }
    }

    if (fs.existsSync(eruptionsFile)) {
      const raw = fs.readFileSync(eruptionsFile, 'utf8');
      this.eruptions = JSON.parse(raw);
    }
  }

  /** @returns {number} */
  volcanoCount() { return this.volcanoes.size; }

  /** @returns {number} */
  eruptionCount() { return this.eruptions.length; }

  /**
   * @param {number} volcanoNumber
   * @returns {object | undefined}
   */
  getByNumber(volcanoNumber) {
    return this.volcanoes.get(Number(volcanoNumber));
  }

  /**
   * Search and filter volcanoes.
   *
   * @param {object} filters
   * @param {string}  [filters.query]          Free-text search across name, country, region, etc.
   * @param {string}  [filters.country]
   * @param {string}  [filters.region]         volcanicRegion
   * @param {string}  [filters.volcanoType]    primaryVolcanoType
   * @param {string}  [filters.rockType]       dominantRockType
   * @param {string}  [filters.tectonicSetting]
   * @param {string}  [filters.epoch]          "Holocene" | "Pleistocene"
   * @param {number}  [filters.minElevation]
   * @param {number}  [filters.maxElevation]
   * @param {number}  [filters.minLatitude]
   * @param {number}  [filters.maxLatitude]
   * @param {number}  [filters.minLongitude]
   * @param {number}  [filters.maxLongitude]
   * @param {number}  [filters.limit]          Max results (default 100)
   * @param {number}  [filters.offset]         Pagination offset (default 0)
   * @returns {{ volcanoes: object[], total: number, filters: object }}
   */
  search(filters = {}) {
    const all = Array.from(this.volcanoes.values());
    const matched = all.filter(v => matchesFilters(v, filters));

    const offset = Number(filters.offset) || 0;
    const limit = Number(filters.limit) || 100;
    const page = matched.slice(offset, offset + limit);

    return { volcanoes: page, total: matched.length, filters };
  }

  /**
   * Get sorted distinct values for a given volcano field.
   * Useful for populating filter dropdowns.
   *
   * @param {string} field  e.g. 'country', 'volcanicRegion', 'primaryVolcanoType'
   * @returns {string[]}
   */
  distinctValues(field) {
    const values = new Set();
    for (const v of this.volcanoes.values()) {
      const val = String(v[field] || '').trim();
      if (val) values.add(val);
    }
    return Array.from(values).sort();
  }

  /**
   * Get eruptions for a specific volcano.
   * @param {number} volcanoNumber
   * @returns {object[]}
   */
  getEruptions(volcanoNumber) {
    const n = Number(volcanoNumber);
    return this.eruptions.filter(e => e.volcanoNumber === n);
  }
}

// ── Internal filter helpers ────────────────────────────────────────────────

function matchesText(value, query) {
  return String(value || '').toLowerCase().includes(query.toLowerCase());
}

function matchesExact(value, filter) {
  if (!filter) return true;
  return String(value || '').toLowerCase() === filter.toLowerCase();
}

function matchesRange(value, min, max) {
  const n = Number(value);
  if (min !== undefined && n < min) return false;
  if (max !== undefined && n > max) return false;
  return true;
}

function matchesFilters(v, filters) {
  if (filters.query) {
    const q = filters.query;
    const hit =
      matchesText(v.volcanoName, q) ||
      matchesText(v.country, q) ||
      matchesText(v.volcanicRegion, q) ||
      matchesText(v.volcanicRegionGroup, q) ||
      matchesText(v.primaryVolcanoType, q) ||
      matchesText(v.dominantRockType, q) ||
      matchesText(v.tectonicSetting, q) ||
      matchesText(v.lastKnownEruption, q) ||
      matchesText(String(v.volcanoNumber), q);
    if (!hit) return false;
  }

  if (!matchesExact(v.country, filters.country)) return false;
  if (!matchesExact(v.volcanicRegion, filters.region)) return false;
  if (!matchesExact(v.primaryVolcanoType, filters.volcanoType)) return false;
  if (!matchesExact(v.dominantRockType, filters.rockType)) return false;
  if (!matchesExact(v.tectonicSetting, filters.tectonicSetting)) return false;
  if (filters.epoch && v.epoch !== filters.epoch) return false;

  if (!matchesRange(v.elevation, filters.minElevation, filters.maxElevation)) return false;
  if (!matchesRange(v.latitude, filters.minLatitude, filters.maxLatitude)) return false;
  if (!matchesRange(v.longitude, filters.minLongitude, filters.maxLongitude)) return false;

  return true;
}

module.exports = VolcanoDataManager;
